[target.x86_64-unknown-linux-gnu]
linker = "clang"
rustflags = [
  "-Clink-arg=-fuse-ld=mold",
  "-Zcodegen-backend=cranelift",
]

[build]
rustc-wrapper = "sccache"

[unstable]
codegen-backend = true

[profile.dev]
opt-level = 1
codegen-backend = "cranelift"
package."*" = { opt-level = 3 }
